spring.datasource.url=jdbc:mysql://localhost:3306/VersionControl
spring.datasource.username=root
spring.datasource.password=MainProject-0909
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html